### ISSUE TITLE
Authorization: refactoring

### ISSUE THREAD

**Issue by annashamray** [GemeenteUtrecht/zaakafhandelcomponent#224]
Parent user story for all refactoring tasks

Concept: https://github.com/GemeenteUtrecht/ZGW/pull/685

**Approaches:**
We have two options:
1. use one model to store both blueprint and atomic permissions
2. use two separate models to store them.

In order not to do the same work twice, we can try both approaches sequentially: first, we can build a working POC with the first approach and then tweak it to explore the second option.  

**Technical steps:**
* [x] Model layer (#225) 
    - [x] create base `Policy` (or `Blueprint`) class which will include serializer to validate `policy` data and a function to check permissions for a particular object (zaak/doc). Add it to `Permission` class
    The structure should be like this:
  ```yaml
  Permission:
      name
      description
      policy:
          blueprint_serializer
          has_access
  ```

    - [x] create model `PermissionDefinition`. See detail in https://github.com/GemeenteUtrecht/ZGW/pull/685. When the data is saved `policy` field should be validated on `blueprint_serializer`. 
    - [x]  `User` model should have m2m relations with `PermissionDefinition`. `User` model should have `permission_definitions` method/property which gathers all related permission definitions including those in `AuthorizationProfile` objects.
    - [x] In the `PermissionDefinition` admin page a description of the `policy` field should be displayed, which depends on the value of the `permission` attribute. (Nice to have)

* [x] (#226) Rule predicates
There are two options how to refactor rule predicates:
1. Permissions are defined only on `PermissionDefinition` data and rules are not needed. For example, if the user is an advisor and they need access to zaak-detail page, the atomic `PermissionDefinition` object would be created with permissions for a particular zaak. It can be done automatically using notifications or manually by administrators. In this case, the rules backend can be removed. Permission check can be performed only in permission mixin. 
2. We will have permissions defined both in `PermissionDefinition` and rules. In this case, a generic rule should check if the user has atomic access or policy access to the object. All rules should be tested only when the object (zaak or doc) exists.

@sergei-maertens Which options do you prefer? I like the first one better because in this case, we have all permission definitions in one place which can be conveniently accessed via DB queries 

Upd. the 1st option has been chosen

* [x] (#227) Filtering list of zaken.
    - [x] add a method `filter_es (search: Search) -> Search` to `Policy` class to update an ES search on the policy blueprint. 
    - [x] In the ES search iterate over all `PermissionDefinition` objects with blueprints and use their `filter_es` methods
    - [x] add atomic objects the user has access to ES search
    -  ~~If rule predicates are left update the search with the logic from them~~ 

* [x] ZAC endpoints: 
  For all endpoint groups: 
  - create subclasses of `Policy` class for every permission with it's own `blueprint_serializer` 
  - test refactored authorization for all bff endpoints
 
  Endpoint groups:
    - [x] accounts (#238)
    - [x] camunda (#248)
    - [x] core (#240)
    - [x] meta (#239)
    - [x] dowc (#248)
    - [x] kownsl (#240)
    - [x] search (#248)
    - [x] workstack (#240)

* [x] Explore the second approach (#266): 
    - [x] Separate atomic and blueprint permissions into two models
    - [x] tweak rule predicates and permission mixins to use it
    - [x] tweak ES search function to use it
    - [x] assess performance\readability comparing to the first approach (comparison - https://gist.github.com/annashamray/c236d26752f5b781d6d0f5dc5e2c5528)

* [x] Make new authorizations work with old ZAC views (nice to have) (#252)
* [x] remove old code (#252)

**Related questions:**
* Should we remove atomic permission to read zaak for the zaak behandelaar if the related rol is deleted?
* How to refactor relations between `AccessRequest` and `PermissionDefinition`. Perhaps `AccessRequest` should be 'through' table between `User` and `PermissionDefinition`

**Upd.** The second approach (refactoring with two permission models) has beem chosen

**Comment by sergei-maertens** [comment]
> @sergei-maertens Which options do you prefer? I like the first one better because in this case, we have all permission definitions in one place which can be conveniently accessed via DB queries

let's do the first. DRF permission classes kind of work like rules predicates, and if needed, we can always bring back rules.
