### ISSUE TITLE
Editing of case relevant data

### ISSUE THREAD

**Issue by damm89** [GemeenteUtrecht/zaakafhandelcomponent#229]
An end user needs to be able to edit certain case attributes, details and relevant information.

This issue is related to: https://github.com/GemeenteUtrecht/ZGW/issues/607, https://github.com/GemeenteUtrecht/ZGW/issues/608, https://github.com/GemeenteUtrecht/ZGW/issues/609.

**BACKEND** (@damm89 ):
- [x] Implement endpoint for case details: https://github.com/GemeenteUtrecht/ZGW/issues/607 is fixed by: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/216.
See the api docs here: https://zac-test.utrechtproeftuin.nl/api/docs/#operation/core_cases_partial_update.
- [x] Implement endpoint for editing case roles: https://github.com/GemeenteUtrecht/ZGW/issues/609 (next sprint)
- [x] Implement endpoint for editing case properties: https://github.com/GemeenteUtrecht/ZGW/issues/608 (needs further development in the standaard)

**FRONTEND** (@kelvincy):

- [x] Editing of case details for issue: https://github.com/GemeenteUtrecht/ZGW/issues/607
- [x] Editing of case roles for issue: https://github.com/GemeenteUtrecht/ZGW/issues/609
~~Editing of case properties for issue: https://github.com/GemeenteUtrecht/ZGW/issues/608~~ (needs further refinement)
