### ISSUE TITLE
Implement prototype scrum/dashboard functionality

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/zaakafhandelcomponent#410]
The development tasks taken from https://github.com/GemeenteUtrecht/ZGW/issues/892

**Tasks**

- [ ] Add the relevant models
    - [ ] `Board`
        - name
        - uuid
        - slug (unique, derived from name)
        - created
        - modified
    - [ ] `BoardColumn`
        - uuid
        - name
        - board (FK)
        - slug
        - order
        - created
        - modified
    - [ ] `BoardItem`
        - uuid
        - objectType (initially only zaken are supported)
        - object (url -> zaak API resource URL) with unique constraint (an item can only be on a single board)
        - board (FK)
        - column (FK) (validate that the column.board is the same as board -> can't move an item to another board)
- [ ] FB must be able to create and manage boards
- [ ] Set up API endpoints
    - [ ] Proper documentation
    - [ ] Endpoint to retrieve a (list of) board(s). Serialize the board columns in the response to avoid having to do another lookup.
    - [ ] Endpoint to retrieve items for a given board (querystring param to filter on board). Items should expose the objectType, object, column fields
    - [ ] Endpoint to delete board items (= remove item from board)
    - [ ] Endpoint to create board items (= add an item to a board)
    - [ ] Endpoint to update board items (= move to another column)
- [ ] Set up API notification subscription
    - [ ] On Zaak destroy action -> remove board item
