### ISSUE TITLE
Add support to pre-existing Documenten API resources to zaak documents

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/zaakafhandelcomponent#435]
Currently the BFF endpoint supports adding documents to cases by uploading a file from the local filesystem (see https://zac-test.utrechtproeftuin.nl/api/docs/#operation/core_cases_document_create)

This requires the following fields: `file`, `informatieobjecttype`. That information is used to create the document in the Documenten API, which returns a resource URL.

This resource URL is then used, together with the case URL where the document is being added, to create a `ZaakInformatieobject` in Open Zaak, which relates the case and the document.

Given that the Contezza document browse/search component allows us to browse the Alfresco file system rather than the local file system and create Document API documents from them, we receive a Documenten API resource URL.

This resource URL can then be used to relate the document to the case.

**Task**

- Extend the existing BFF endpoint:
    - [x] Add support for `document` parameter in the request body, which must be a URL to an `EnkelvoudigInformatieobject` in a Documents API (Open Zaak validates this, we can just pass it through)
    - [x] Make `file` and `informatieobjecttype` optional fields
    - [x] Validate that either `document` or (`file` and `informatieobjecttype`) are provided - so you either relate an existing document or create and relate a new one.

**Comment by svenvandescheur** [comment]
I think this one done?
