### ISSUE TITLE
Add option to index_zaken management command to only index x most recent cases

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/zaakafhandelcomponent#445]
This would help running the management command for small delta's of data rather than the entire dataset and can also be set-up as a cron maybe for corrective actions in case notifications are lost/not picked up.

**tasks**

- [x] Implement `src/manage.py index_zaken --reindex-last=100`: https://github.com/GemeenteUtrecht/zaakafhandelcomponent/pull/446
- [x] Ensure the index is not dropped and re-created, but rather just "updated"
- [x] To account for possible lost "delete" notifications, implement a management command `src/manage.py check_for_deleted_zaken`
    - [x] Check the indexed zaken and verify that they still exist in the Zaken API
    - [x] If they are gone from the Zaken API, delete from the index

**Comment by sergei-maertens** [comment]
Fixed via #446
